<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.18.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JCA.WorkSpace.Domain\JCA.WorkSpace.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Email\Assets\facilities.png">
      <LogicalName>email-guides.facilities.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Email\Assets\admin.png">
      <LogicalName>email-guides.admin.png</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Email\Assets\gestor.png">
      <LogicalName>email-guides.gestor.png</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
