<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.75.0" />
    <PackageReference Include="MassTransit" Version="8.3.6" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.8" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JCA.WorkSpace.Domain\JCA.WorkSpace.Domain.csproj" />
    <ProjectReference Include="..\JCA.WorkSpace.Infrastructure.Data\JCA.WorkSpace.Infrastructure.Data.csproj" />
  </ItemGroup>

</Project>
